# Config DS
spring.datasource.url=jdbc:postgresql://localhost:5432/qa_db
spring.datasource.username=odoo
spring.datasource.password=odoo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true

server.port=9090
server.servlet.context-path=/api/v1

# Para cargar data desde un archivo .sql
#spring.sql.init.mode=NEVER
#spring.sql.init.data-locations=classpath:db/users.sql, classpath:db/movies.sql, classpath:db/ratings.sql
#spring.jpa.defer-datasource-initialization=true%